name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "latest"
      - name: Checkout
        uses: actions/checkout@v3
      - name: install PNP
        run: yarn install
      - name: build PNP
        run: yarn build
      - name: run PNP
        run: yarn dev &
        # Allow some time for the server to start
      - name: Wait for server to start
        run: sleep 30
      - name: run tests
        run: yarn test
      - name: Archive test results
        if: failure() # This ensures that the results are always uploaded, even if the tests fail
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos/*.mp4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      #- name: Cypress run
      #  uses: cypress-io/github-action@v5
      #  with:
      #    start: yarn test
