name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Yarn Dependencies
        uses: actions/cache@v2
        with:
          path: |
            .yarn/cache
            .yarn/unplugged
            .yarn/build-state.yml
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install
      #      - name: Build
      #        run: yarn build
      - name: Start Server
        run: |
          yarn dev &
          npx wait-on http://localhost:3000
      - name: run tests
        run: yarn test

      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: cypress/videos/*.mp4
